# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 0a686067882cbf5896c7b59c4a51ed1df641f56b7db3fe014a56ba7c84fcf8a9fd8c7d957fc0817b528cad02c9885e355e83f658439a0ffa4f76c6325827cc22
  
test:
  secret_key_base: dc3f3463c343695ad76b4d3942672e878bab2fbc977f24eca1c86ea64408a776e6e4a91fab9a2c527d133f50f60807e91fbbe70a1d4dd1552d76d66b313b6bd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
